### ISSUE TITLE
Mac OS X go get fails

### ISSUE THREAD

**Issue by akamensky** [andlabs/ui#108]
Commented out code is not so commented out actually:

    akamensky@macbook:~/IdeaProjects/test/src$ go get github.com/andlabs/ui
    # github.com/andlabs/ui
    github.com/andlabs/ui/areahandler.go:5:11: fatal error: 'ui.h' file not found
     #include "ui.h"
              ^
    1 error generated.

**Comment by andlabs** [comment]
While both libui and package ui are still in alpha a simple go get won't suffice. I'll post build instructions later or tomorrow.

**Comment by akamensky** [comment]
@andlabs If it is broken, maybe it should be on separate branch, something like `dev`? 

I mean I've tried this project just a week ago and it worked fine on my test app with `go get` so I am really surprised that when I come back it does not work and also will have an extra build process. 

The sole idea of having package managers such as Maven, NPM or `go get` in this instance is to simplify those extra build steps. Would you consider incorporating these steps into general go get process?

**Comment by matrixik** [comment]
Oh please. It's _alpha_. Why should he waste time to create branches now? Leave that to time when all libs are stable.

**Comment by andlabs** [comment]
You're probably right; I should have started this work in a separate branch. I so far haven't done so for two main reasons: a) I'm not really comfortable with working in branches in general, b) since this is effectively a solo project with a linear progression there aren't really going to be branches to merge in the first place.

Our ideas of stability are different, and I guess it's my fault for letting this repo sit for so long without an update :/ But in reality package ui as it was before this week was very buggy in certain places (especially on Windows) and interop with the Go runtime and its various changes in 1.5 was not done well enough that I can guarantee you will get hit by something changing its pointer address from under you. This new rewrite fixes both issues, and once I can readd the last few missing bits (Grid, Table) and one last drawing facility (text) I can finally push everything up to a beta 1 (which will come with the libui library as part of the repo, no extra installation needed).

In the meantime, if you want to work with what was available last week I tagged it off; it's `pre-libui`. I'll update the README to point this out. I'm not sure what else I can do in the meantime to make the development cycle better, but I would definitely like to know.
