### ISSUE TITLE
Implement NewPasswordEntry

### ISSUE THREAD

**Issue by emersion** [andlabs/ui#145]
To do this, we need to update static builds. Do you plan to release a new version of libui soon?

Also, do you cross-compile libui? If so, how to do it?

**Comment by andlabs** [comment]
I intend to release a new version fo libui sometime soon. I'm waiting for a few contributions from others first; my own stuff should be done soon, though. The next release also fixes some issues with the static build that I need to fix in order to get this working; things I didn't expect happened :( After that release, I'll sync the APIs and fix static issues on the Go side.

You can cross-compile if you have the necessary tools and run cmake correctly. I don't personally do it, but I think I have tried it before? I forget now; sorry.

**Comment by emersion** [comment]
Okay, I just opened a PR (#146) to support the latest libui `intmax_t` changes and password+search entries.

I can help to sync APIs if necessary.

**Comment by andlabs** [comment]
Merged with #277.
