### ISSUE TITLE
password field api

### ISSUE THREAD

**Issue by joeblew99** [andlabs/ui#183]
hey everyone,

old code is : passwordTextField := ui.NewPasswordField()

whats the new way to do this ?

**Comment by emersion** [comment]
Please RTFM: https://godoc.org/github.com/andlabs/ui

The function is `NewPasswordEntry`

**Comment by joeblew99** [comment]
@emersion 

On that page i there is no "password" text .

also when i try NewPasswordEntry it.

I did a go get on the lib this morning....

**Comment by emersion** [comment]
My bad. This repo hasn't this function yet. If you need it, you can use `github.com/ProtonMail/ui` (docs: https://godoc.org/github.com/ProtonMail/ui).

The corresponding PR is here: https://github.com/andlabs/ui/pull/169

**Comment by joeblew99** [comment]
@emersion  

thanks.  I will start to use your fork for now.

closing.

**Comment by gedw99** [comment]
Did this report get updated ?
According to the git repository it's been about 4 months since an update has occurred.

Basically I am disappointed that the project is stalled :)
The code is good needs smallish bugs fixed.
I guess the problem is that few SEC's have the skills to fix the code since it's not just golang ?

**Comment by emersion** [comment]
It seems that this repo won't change until a new libui version is released.

Maybe it would be a good idea to fork libui and ui to be able to move the project forward.

**Comment by gedw99** [comment]
@emersion 
i am nervous about forking because:
1. who can maintain it ? you ß I coudl help a bit, but not much of a c coder.

2. Will the code still work ok with the https://github.com/andlabs/libui over time ?

3. Is the curent maintainer cool about it ?

Are any of these issues issues :) ?

**Comment by emersion** [comment]
@gedw99 Instead of making a fork, a far better solution would be to add another maintainer to ui and libui. That would allow PRs to be merged at least. The problem is that nobody has contributed enough yet (@andlabs, what do you think?).

To reply to your questions:
1. I'm not a C coder either, so I would probably only be able to fix small issues, but not to solve harder problems (like tables, images and so on)
2. What do you mean? If we want to add new components, we'll have to change code in libui too, so using a andlabs/libui build won't work anymore.
3. @andlabs, do you think you'll be able to spend again some time to maintain this library? From what I've understood, it's not possible for now (and you're not to blame, not at all!).

**Comment by gedw99** [comment]
@emersion thanks for pushing this along.

I changed my comments - i really was not sure what i was saying. Just speculating, so better i just shutup. :)

Anything that makes it get better for me and all i am only too happy to encourage and help in any way i can.

I agree too. Add another maintainer, rather than fork - it will allow things to move forward, and also maybe i can send some PR's and get them merged by the maintainer. But who ? You i guess so you no longer have to have a fork, but can help on the main tree ?
