### ISSUE TITLE
Feature request: Richer elements

### ISSUE THREAD

**Issue by vhakulinen** [andlabs/ui#54]
This one might be huge thing to do.

Would be awesome if there would be more options that OnClicked(), SetText(), Text(). Things like richer text (color, links etc.), OnDoubleClick(), MouseOver() (like hover in css), ForegroundColor, BackgroundColor, inline images etc. stuff like that.

I haven't played with the Area widget so I'm not sure, but with Area you pass AreaHandler which allows you to have more control over the field. Same kind of behavior could be added to other fields which would allow the OnDoubleClick and MouseOver etc. events and when you have control to those events you could easily dynamically change e.g. BackgroundColor of text if the element just has the option to change that.

There wouldn't be need to code every event (OnDoubleClick, MouseOver etc.) to the ui library if you just have the AreaHandler'ish handler for every field (optionally) and let the user chose if she/he wants to handle the events.

**Comment by andlabs** [comment]
Yes, a lot of what you describe is the point of uiArea and formatted text (which has a final API that's now in libui and that needs to be moved here once Alpha 4 is released). Some of the other points in this thread are covered by other issues (in particular andlabs/libui#313 as well as a handful of others dedicated to hyperlinks). On that note, closing, since everything here has been accounted for and taken into consideration elsewhere, if not already done. If I am missing anything, please let me know!
