### ISSUE TITLE
Feature Request: Web View

### ISSUE THREAD

**Issue by lunny** [andlabs/ui#63]

**Comment by kalopsia** [comment]
Is there any news regarding to the topic?

**Comment by colorsocean** [comment]
:+1:

**Comment by lukevers** [comment]
:+1:

**Comment by andlabs** [comment]
I decided to start this last rewrite by setting it up such that it would be possible to add your own controls to the UI from the get-go (the implementation of most of the standard controls will use this system themselves). [Here's an example of the C API that would use (in this case, on Windows).](https://github.com/andlabs/ui/blob/fc3456f5e1b4e3dd265603d9406d0348f6878548/new/ui_windows.h#L11) Hopefully, this should make it possible to add a WebKit view somehow. I'd most likely do it as a subpackage (rather than as part of the core ui package).

**Comment by andlabs** [comment]
This is not likely going to happen.

On OS X, it simply is not enough that you need to have every action be on one thread; you also need to have them be on the very first thread created by the operating system. Go does not guarantee that code will stay on one OS thread through its lifetime, so we cannot ensure that this is the case (and calling `runtime.LockOSThread()` from `main()` is betting on luck; this must be a contractual guarantee in the runtime documentation). Fortunately, an undocumented set of APIs allow Core Foundation's notion of the main thread to be altered, so Cocoa, for the most part can be fooled. Any code that checks the main thread using Core Foundation or Cocoa functions will be similarly fooled.

Some wackjob decided it'd be a great idea to *also* have this functionality exposed by pthreads! The function is called `pthread_main_np()`, and is present in several other BSDs as well as OS X. And there is no undocumented workaround (unless I start clobbering random bytes of the internal pthread data structures).

[Guess which one WebKit uses.](https://github.com/WebKit/webkit/blob/master/Source/WTF/wtf/mac/MainThreadMac.mm#L92)

So unless there's a way to fool `pthread_main_np()` into returning main for any given pthread, we're out of luck here. Suggestions welcome. Compiling WebKit from source with a patch is not an option unless you want a package ui/webkit to take 5 hours to compile.

**Comment by andlabs** [comment]
https://github.com/rentzsch/mach_override/ ooh, this seems to work perfectly to override `pthread_main_np()`~

**Comment by heramerom** [comment]
👍

**Comment by andlabs** [comment]
Merged with andlabs/libui#315.
