### ISSUE TITLE
Feature request: GDI-like drawing interface for Areas

### ISSUE THREAD

**Issue by JamesDunne** [andlabs/ui#69]
I've got a simulator app written in C targeting the Win32 API, exlusively using GDI to render the UI. There aren't any standard widgets involved; it's all custom rendering. I'd love to port this application to Go using your UI framework so that I can achieve easy portability but there isn't a canvas-like drawing API exposed here. Instead, your `Paint` event returns an `image.RGBA` but I have no direct way to draw to it.

I've ported my simulator app to JavaScript and rewrote the GDI drawing commands to target the `<canvas>` drawing API. If not GDI, then at least a basic HTML5 canvas drawing API would suffice so that I can port that straightforward JavaScript code over to Go and not have to deal with `SelectObject` and brushes and all that nonsense.

**Comment by andlabs** [comment]
I have that planned.

What I will be providing at some point in the future is a package vectorgfx that provides a consistent interface for vector graphics interfaces like GDI, cairo, Core Graphics (the three that package ui will use), and likely others. Package ui will provide a `SysArea` control that is like `Area` except its `AreaHandler.Paint()` will provide the system drawing surface (HDC, cairo_t*, CGContextRef) that you can pass into vectorgfx.

I do not know when this will happen, though.

**Comment by JamesDunne** [comment]
Nice! In the mean time, I've found the draw2d library from code.google.com and will use that. It looks like it should do the trick for my purposes.

**Comment by andlabs** [comment]
Yes, that would work for now. It won't take advantage of anything in the acceleration department that GDI has to offer, but it's been around for a while and a lot of people use it, so... =P

**Comment by andlabs** [comment]
Notes:

In order for a package like vectorgfx to work in Go without major issues, everything needs to have well-defined thread affinity, because with Go there are no guarantees that a goroutine and an OS thread have a 1:1 relationship (unless we limit YOU the application programmer to one OS thread).

Thread affinity of GDI:

http://blogs.msdn.com/b/oldnewthing/archive/2005/10/11/479587.aspx DCs: same thread that created must destroy, but other than that no issue; not a problem for package ui, might be an issue for package vectorgfx depending on what creation interfaces I provide

http://blogs.msdn.com/b/oldnewthing/archive/2005/10/13/480569.aspx GDI objects: any thread

http://blogs.msdn.com/b/oldnewthing/archive/2012/11/09/10367057.aspx Printer DCs. Here's the issue. Eventually I'm going to need to add a way to access printers, both to package ui (where the printer dialog will return an HDC because I don't see a way to get one later; TODO) and package vectorgfx (as a general utility), and a lot of printer drivers seem fickle and seem to give DCs thread affinity. This will definitely be an issue for package ui...

**Comment by andlabs** [comment]
Now available!

**Comment by JamesDunne** [comment]
Nice!
